### ISSUE TITLE
What are the login credentials?

### ISSUE THREAD

**Issue by CHJ85** [robert-axelrod/google-accounts-creator#1]
Hi there. I'm not sure if this app still works or not. But I tried it out and it's asking for some login ### credentials. What is this about?

**Comment by XEVON01** [comment]
I think the credentials are paid

**Comment by robert-axelrod** [comment]
You should buy it on the website https://youtube-booster.space/google-accounts-creator/

**Comment by Joseph81271** [comment]
I don't wanna steal my mommys fucking shitty ass credit card. How tf do i use this shit with only 1 dollar?
